"""Pydantic models for pytest-httpchain test scenarios.

This package defines the data models used to validate and represent HTTP test
scenarios, including requests, responses, verification steps, and configuration.
All models use Pydantic V2 with discriminated unions for flexible body types.

Key models:
- Scenario: Root model representing a complete test scenario
- ClientConfig: The scenario's shared HTTP client (base URL, default headers, pool)
- Stage: Individual test stage with request and response processing
- Request: HTTP request configuration (method, URL, headers, body, auth)
- Auth: authentication, built in (basic, digest, bearer) or a user function
- Verify: Response verification rules (status, headers, JMESPath, body, expressions)
- Save: Data extraction from responses (JMESPath, regex, substitutions, user functions)
"""

from pytest_httpchain.models.entities import (
    Auth,
    AuthCredentials,
    Base64Body,
    BasicAuth,
    BearerAuth,
    BinaryBody,
    ClientConfig,
    CombinationsParameter,
    DigestAuth,
    FilesBody,
    FormBody,
    FunctionsDict,
    FunctionsList,
    FunctionsSubstitution,
    GraphQLBody,
    HeaderMatcher,
    IndividualParameter,
    JMESPathExpectation,
    JMESPathMatcher,
    JMESPathSave,
    JsonBody,
    ParallelConfig,
    ParallelConfigBase,
    ParallelForeachConfig,
    ParallelRepeatConfig,
    Parameter,
    Parameters,
    RegexCapture,
    RegexSave,
    Request,
    RequestAuth,
    RequestBody,
    ResponseBody,
    Responses,
    ResponseStep,
    Save,
    SaveStep,
    Scenario,
    SSLConfig,
    Stage,
    Substitution,
    Substitutions,
    SubstitutionsSave,
    TextBody,
    UserFunctionCall,
    UserFunctionKwargs,
    UserFunctionName,
    UserFunctionsSave,
    VarsSubstitution,
    Verify,
    VerifyStep,
    XmlBody,
    normalize_list_input,
    parametrize_values_contain_template,
    validate_rendered_scenario_auth,
    validate_rendered_verify,
)
from pytest_httpchain.models.types import JSON_TYPE_NAMES, check_json_schema, is_relative_url, is_status_class, json_schema_validator_class, regex_group

__all__ = [
    "Scenario",
    "Stage",
    "ParallelConfig",
    "ParallelConfigBase",
    "ParallelForeachConfig",
    "ParallelRepeatConfig",
    "Parameters",
    "Parameter",
    "CombinationsParameter",
    "IndividualParameter",
    "Responses",
    "ResponseStep",
    "VerifyStep",
    "SaveStep",
    "Verify",
    "HeaderMatcher",
    "JMESPathExpectation",
    "JMESPathMatcher",
    "ResponseBody",
    "Save",
    "JMESPathSave",
    "RegexSave",
    "RegexCapture",
    "SubstitutionsSave",
    "UserFunctionsSave",
    "Substitutions",
    "Substitution",
    "FunctionsSubstitution",
    "VarsSubstitution",
    "Request",
    "RequestAuth",
    "RequestBody",
    "JsonBody",
    "XmlBody",
    "FormBody",
    "TextBody",
    "Base64Body",
    "BinaryBody",
    "FilesBody",
    "GraphQLBody",
    "FunctionsDict",
    "FunctionsList",
    "UserFunctionCall",
    "UserFunctionName",
    "UserFunctionKwargs",
    "Auth",
    "AuthCredentials",
    "BasicAuth",
    "DigestAuth",
    "BearerAuth",
    "SSLConfig",
    "ClientConfig",
    "JSON_TYPE_NAMES",
    "check_json_schema",
    "is_relative_url",
    "is_status_class",
    "json_schema_validator_class",
    "regex_group",
    "parametrize_values_contain_template",
    "normalize_list_input",
    "validate_rendered_scenario_auth",
    "validate_rendered_verify",
]
