import warnings

from .entities import (
    Base64Body,
    BinaryBody,
    CombinationsParameter,
    FilesBody,
    FormBody,
    FunctionsDict,
    FunctionsList,
    FunctionsSubstitution,
    GraphQLBody,
    IndividualParameter,
    JsonBody,
    ParallelConfig,
    Parameter,
    Parameters,
    Request,
    RequestBody,
    ResponseBody,
    Responses,
    ResponseStep,
    Save,
    SaveStep,
    Scenario,
    SSLConfig,
    Stage,
    Substitution,
    Substitutions,
    TextBody,
    UserFunctionKwargs,
    UserFunctionName,
    VarsSubstitution,
    Verify,
    VerifyStep,
    XmlBody,
)
from .types import check_json_schema

__all__ = [
    "Scenario",
    "Stage",
    "ParallelConfig",
    "Parameters",
    "Parameter",
    "CombinationsParameter",
    "IndividualParameter",
    "Responses",
    "ResponseStep",
    "VerifyStep",
    "SaveStep",
    "Verify",
    "ResponseBody",
    "Save",
    "Substitutions",
    "Substitution",
    "FunctionsSubstitution",
    "VarsSubstitution",
    "Request",
    "RequestBody",
    "JsonBody",
    "XmlBody",
    "FormBody",
    "TextBody",
    "Base64Body",
    "BinaryBody",
    "FilesBody",
    "GraphQLBody",
    "FunctionsDict",
    "FunctionsList",
    "UserFunctionName",
    "UserFunctionKwargs",
    "SSLConfig",
    "check_json_schema",
]


# Suppress Pydantic UserWarning about json attribute shadowing BaseModel.json method
warnings.filterwarnings("ignore", message='.*"json".*"BaseModel".*', category=UserWarning, module="pydantic")

# Suppress Pydantic UserWarning about json attribute shadowing BaseModel.schema method
warnings.filterwarnings("ignore", message='.*"schema".*"BaseModel".*', category=UserWarning, module="pydantic")
